CREATE TABLE KH_STUDENT (
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN KH_STUDENT.STD_NO IS '학생 번호';
COMMENT ON COLUMN KH_STUDENT.STD_NAME IS '학생 이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE IS '학생 나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR IS '전공';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE IS '입학일';

SELECT * FROM KH_STUDENT;

CREATE SEQUENCE SEQ_STD_NO NOCACHE;

INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '정석원', 35, '영화영상학', '2025-09-10');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '안재훈', 28, '코딩학', '2025-09-10');
INSERT INTO KH_STUDENT VALUES (SEQ_STD_NO.NEXTVAL, '전재민', 24, '코딩학', '2025-09-10');

COMMIT;

SELECT * FROM KH_STUDENT;